# Generated by Django 4.1.4 on 2023-03-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restApi_App", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="itemLocation",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="itemName",
            new_name="title",
        ),
    ]
