# Generated by Django 4.1.4 on 2023-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restApi_App", "0002_rename_itemlocation_item_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="date_added",
            new_name="created_at",
        ),
    ]
