# Generated by Django 4.1.4 on 2023-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restApi_App", "0005_alter_item_content_alter_location_locationname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.TimeField(),
        ),
    ]
