# Generated by Django 4.1.4 on 2023-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restApi_App", "0006_delete_location_alter_item_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
